### ISSUE TITLE
add 5XX fields to authorities display

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/marva-frontend#71]
The display of information related to an agent is helpful, but the display of See Also references is missing.

https://id.loc.gov/authorities/names/n93099439.html

![image](https://user-images.githubusercontent.com/8515603/128524678-8dc9caf3-5020-4da3-838d-a25b20e7f710.png)

A "see also" reference to Mark Twain is missing.

If possible, the "see also" references should display under the Variants and before the MADS collection.

**Comment by thisismattmiller** [comment]
Note to self: 
The lookup context feature makes use of the .madsrdf_raw.jsonld endpoint which doesn't contain these relational properties. 

For this feature to work we need to implement a two step lookup, the quick .madsrdf_raw.jsonld and then a longer async .madsrdf.jsonld that returns additional relationships that populates the display if they wait long enough

**Comment by jodiw01** [comment]
transferred to gitlab
